### PR TITLE
Update SAR extension version to v1.1.0

### PR DESCRIPTION
**Pull request by emmanuelmathot**
- Prepare for release 1.1.0.
- Updated maturity classification to Stable

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
Blocking as I didn't yet review #18

Do you have 6 implementation for SAR for the Stable maturity?

**Review by fabricebrito — APPROVED** [review]
LGTM

**Comment by emmanuelmathot** [comment]
@m-mohr Are we good to release 1.1.0?

**Comment by m-mohr** [comment]
I have it on my todo list, but it competes with paid jobs. I should be able to get to it this month though, but no promises.

**Review by m-mohr — APPROVED** [review]

**Comment by fabricebrito** [comment]
Thank you both @emmanuelmathot and @m-mohr

**Pull request merged**
